version: '3.1'
services:

  vpn-sessions:
    container_name: sessions
    build: .
    volumes:
     - azure_share_name:/audit_export
    image: az_ctr_repo.azurecr.io/sessions
    ports:
      - 80:80
      - 587:587